CREATE TABLE short_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code VARCHAR(32) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_short_urls_short_code UNIQUE (short_code)
);

CREATE TABLE click_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id BIGINT NOT NULL,
    clicked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    referrer VARCHAR(1024),
    user_agent VARCHAR(512),
    ip_hash VARCHAR(64),

    CONSTRAINT fk_click_events_short_url
        FOREIGN KEY (short_url_id)
        REFERENCES short_urls(id)
);

CREATE INDEX idx_click_events_short_url_id
    ON click_events(short_url_id);

CREATE INDEX idx_click_events_clicked_at
    ON click_events(clicked_at);